/*
 * Electrode Native Navigation
 * Electrode react native Navigation api. 
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * Do not edit the class manually.
 */

import ErnNavigationRequests from '../../src/api/ErnNavigationRequests';

describe('ErnNavigationApi', function () {
  let requests;
  beforeEach(function () {
    let requestHandler;
    requests = new ErnNavigationRequests({
      registerRequestHandler(name, handler) {
        requestHandler = handler;
      },
      sendRequest(name, data) {
        requestHandler && requestHandler(data);
        return Promise.resolve(data);
      },
    });
  });

  describe('navigate', () => {
    it('sends "navigate" request', () => {
      return requests.navigate('id').then(response => {
        expect(response).toEqual({data: 'id', timeout: undefined});
      });
    });
  });
});
